### ISSUE TITLE
NameError: name 'out_file' is not defined

### ISSUE THREAD

**Issue by KlemensFroehlich** [Rostlab/goPredSim#3] opened 2022-10-24 09:56 UTC
Dear Developers,
I would be very interested in using your tool.
However, I am new to using Python (R User) and ran into some trouble while following the instructions.

I downloaded the seqvec data, and modified the config.txt and installed all dependencies required.

I then change the directory to the main folder and execute:
![image](https://user-images.githubusercontent.com/22170937/197500365-29551a31-1fb9-4528-bf16-92351e791db0.png)

Is it a problem that I am using anaconda?

When I open the mentioned scripts in spyder I can see that it is not happy with the code for some reason, but I do not know enough python to make a lot of sense of it......

Any help would be highly appreciated!
Best, Klemens

**Comment by t03i** [comment] 2023-02-06 10:25
Hi Klemens,
Thanks for your interest in goPredSim, and thank you for your patience. 
The issue you describe was caused by a bug in our code formatting (see #4) and should be fixed now.

**Closed as completed by t03i** 2023-02-06 10:25 UTC
